### ISSUE TITLE
Make it easier to verify logged exception ignoring StackTrace etc.

### ISSUE THREAD

**Issue by weitzhandler** [adrianiftode/Moq.ILogger#2]
First and formost, this is a great library and works great, thank you!

Currently, when providing an exception to be verified, the verification also includes the `StackTrace` property of the exception and some other non relevant data that can never be matched when the exception is thrown internally from the SUT.

Please make it easier to verify exceptions by enabling skipping some irrelevant properties, such as `StackTrace`.

Thank you

**Comment by adrianiftode** [comment]
Hey @weitzhandler, thanks for creating this issue. Can you provide an example just to make sure I properly understand the issue? Thanks.

**Comment by adrianiftode** [comment]
I have also [blogged](https://csharpin.blogspot.com/2020/06/verify-ilogger-calls-with-moqilogger.html) about this library and there is an example about checking some exceptions are logged. Basically is something like:

```csharp
 // Assert
   loggerMock.VerifyLog(c => c.LogWarning(
                 It.Is<Exception>(paymentException => paymentException.Message.Contains("Payment exception")), 
                 "*exception*Reference 2"));
```

**Comment by weitzhandler** [comment]
I actually need to verify against exception type, but apparently, `It.Is<ArgumentOutOfRangeException>(exception => exception.ParamName == expectedParamName && exception.Message == expectedMessage)` seems to be working fine.

Although a bit cumbersome, it's good enough. So I'm gonna go ahead and close this issue.
Thank you so much for your response, and for this great library. I integrated it in my project and refactoring to it was fairly easy!

**Comment by adrianiftode** [comment]
Thanks, I appreciate your feedback and your kind words.
