### ISSUE TITLE
Wildcards are not working as expected

### ISSUE THREAD

**Issue by Jertimmer** [adrianiftode/Moq.ILogger#8]
I just want to start off with a big thanks for this library, I had just started on creating a similar extension to test logging, when I stumbled upon this gem. Absolute life-saver.

I did however come across an issue and I'm not sure whether I'm using the extension wrong, or if it's an actual bug.

Here is my Mock-setup:
`redisClient.Setup(x => x.SetAsync<BuyIntention>(It.IsAny<string>(), It.IsAny<BuyIntention>(), It.IsAny<CancellationToken>())).Throws(new Exception("Exception thrown"));`

The code to log the exception
` _logger.LogError(exception, $"Exception thrown trying to set ID {id} for Aggregate {aggregateId}");`

In my test, I've added the following line to my Assert:
`logger.VerifyLog(c => c.LogError(It.Is<Exception>(e => e.Message.Contains("Exception thrown")), $"*ID {id}*Aggregate {aggregateId}*"));`

Which results in a Moq.VerifyLogException; 
`Expected invocation on the mock at least once, but was never performed:`

Yet, when I remove the wildcards and check for the entire string:
`logger.VerifyLog(c => c.LogError(It.Is<Exception>(e => e.Message.Contains("Exception thrown")), $"Exception thrown trying to set ID {id} for Aggregate {aggregateId}"));`

The test is succesful.

This is an acceptable work-around for now, however, I would like to use the wildcards, since the specifications only state that we should at least log the ID and the AggregateID the code is trying to store in Redis.

**Comment by adrianiftode** [comment]
Thank you @Jertimmer for your appreciation and also for submitting this issue.

A fix has been pushed into the 1.1.9 version.
